name: flt_vndb
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  built_collection: ^5.1.1
  built_value: ^8.4.1
  cached_network_image: ^3.2.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.5
  infinite_scroll_pagination: ^3.2.0
  json_annotation: ^4.7.0
  logging: ^1.0.2
  mutex: ^3.0.0
  provider: ^6.0.3
  tuple: ^2.0.0
  material_design_icons_flutter: "5.0.6996"
  quiver: ^3.1.0
  path_provider: ^2.0.11
  auto_size_text: ^3.0.0
  shared_preferences: ^2.0.15
  rxdart: ^0.27.5
  flutter_bbcode: ^1.1.3
  collection: ^1.16.0
  url_launcher: ^6.1.6
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  json_serializable: ^6.4.1
  built_value_generator: ^8.4.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/languages/
    - assets/platforms/
    - assets/data/
